### PR TITLE
added deploy script

### PR DESCRIPTION
**Pull request by MpinaneRabbit**

### CODE REVIEW

**Comment by CilliersN** [comment]
first comment

**Review by FredJEhlers — COMMENTED** [review]
Does your project not require for version locks? ie the packages that you are using, are you sure you want them to automatically update and possibly break in the future or do you guys not mind. 

`^4.29.1` allows automatic updates so just remove `^` if you want to stop it from updating itself

**Comment by grootendorste** [comment]
Agree with @FredJEhlers , maybe take the ^ away. Although it's not the end of the world.

**Comment by rjacobs31** [comment]
> 
> 
> Does your project not require for version locks? ie the packages that you are using, are you sure you want them to automatically update and possibly break in the future or do you guys not mind.
> 
> `^4.29.1` allows automatic updates so just remove `^` if you want to stop it from updating itself

Disagree. The `yarn.lock` file is supposed to take care of this. As long as your packages aren't inconsistent with the Semver standard, it will install exactly what's in the `yarn.lock` file.
[Source](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install)

**Comment by MpinaneRabbit** [comment]
> Agree with @FredJEhlers , maybe take the ^ away. Although it's not the end of the world.

I made the changes, please review again

**Comment by rjacobs31** [comment]
@MpinaneRabbit Regardless of whether you go with what @FredJEhlers says or with what I say, I highly recommend installing new packages with the `yarn add [package]` command.

If you later need to upgrade packages, I recommend `yarn upgrade-interactive` ([link](https://yarnpkg.com/en/docs/cli/upgrade-interactive#toc-yarn-upgrade-interactive)).

**Review by FredJEhlers — APPROVED** [review]

**Comment by FredJEhlers** [comment]
@MpinaneRabbit changes approved but do take note of what @rjacobs31 has said.

**Review by FredJEhlers — APPROVED** [review]

**Pull request merged**
